# Generated by Django 4.0.3 on 2022-05-19 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(editable=False, max_length=50)),
                ('state', models.CharField(editable=False, max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, editable=False, max_digits=7)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='/default.png', null=True, upload_to='')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
    ]
