# Generated by Django 4.0.3 on 2022-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_warehouse_city_alter_warehouse_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
