# Generated by Django 4.0.3 on 2022-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
