# Generated by Django 4.0.3 on 2022-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_number_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='dateAdded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
