# Generated by Django 4.0.3 on 2022-05-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventoryitem_dateadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='dateAdded',
        ),
    ]
