# Generated by Django 4.0.3 on 2022-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventoryitem_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='available_capacity',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
