# Generated by Django 4.0.3 on 2022-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_warehouse_available_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='available_capacity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
