# Generated by Django 4.0.3 on 2022-05-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
